<?php
/**
 * JSON API: excluded facts for an entity.
 * Queries the SQLite database at data/excluded_facts.db (generated by scripts/generate-excluded-facts-db.py).
 *
 * GET params: subject (entity URI)
 */

require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/sparql.php';
require_once __DIR__ . '/../includes/excluded_facts.php';

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');

$subject = trim($_GET['subject'] ?? '');
if (!$subject) {
    echo json_encode(['error' => 'Missing subject parameter']);
    exit;
}

try {
    $db = openExcludedFactsDatabase();
    if (!$db) {
        echo json_encode(['facts' => []]);
        exit;
    }

    $rows = getExcludedFacts($db, $subject);
    $objectUris = [];
    foreach ($rows as $row) {
        $resolvedObj = resolveExcludedFactObjectUri($row['object']);
        if ($resolvedObj !== null) {
            $objectUris[] = $resolvedObj;
        }
    }
    $excludedEntities = findExcludedEntities($db, $objectUris);

    $facts = [];
    foreach ($rows as $row) {
        $isFullPredUri = strpos($row['predicate'], 'http://') === 0 || strpos($row['predicate'], 'https://') === 0;
        $resolvedPred = $isFullPredUri ? $row['predicate'] : resolvePrefixedUri($row['predicate']);
        $row['predicate_display'] = $isFullPredUri ? uriToPrefixedName($row['predicate']) : htmlspecialchars($row['predicate']);
        $row['predicate_url'] = uriToUrl($resolvedPred);
        $isFullUri = strpos($row['object'], 'http://') === 0 || strpos($row['object'], 'https://') === 0;
        $resolvedObj = resolveExcludedFactObjectUri($row['object']);
        $isPrefixed = !$isFullUri && $resolvedObj !== null;
        if ($isFullUri) {
            $row['object_display'] = uriToPrefixedName($row['object']);
            $row['object_url'] = isset($excludedEntities[$resolvedObj])
                ? excludedEntityResourceUrl($resolvedObj)
                : uriToUrl($row['object']);
        } elseif ($isPrefixed) {
            $row['object_display'] = htmlspecialchars($row['object']);
            $row['object_url'] = isset($excludedEntities[$resolvedObj])
                ? excludedEntityResourceUrl($resolvedObj)
                : uriToUrl($resolvedObj);
        } else {
            $row['object_display'] = htmlspecialchars($row['object']);
            $row['object_url'] = null;
        }
        $facts[] = $row;
    }
    echo json_encode(['facts' => $facts]);
} catch (PDOException $e) {
    echo json_encode(['facts' => [], 'error' => 'Database unavailable']);
}
